// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabasePublishableKey, getSupabaseUrl } from './env';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use browser-safe VITE_* values on the client; fall back to server envs only on SSR.
  const SUPABASE_URL =
    typeof window !== 'undefined'
      ? getSupabaseUrl()
      : getSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY =
    typeof window !== 'undefined'
      ? getSupabasePublishableKey()
      : getSupabasePublishableKey();

  const effectiveKey = SUPABASE_PUBLISHABLE_KEY;

  if (typeof window !== 'undefined' && 'VITE_SUPABASE_SERVICE_ROLE_KEY' in import.meta.env) {
    const message =
      'Supabase service_role key must not be exposed in browser env (VITE_SUPABASE_SERVICE_ROLE_KEY).';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (effectiveKey && isNewSupabaseApiKey(effectiveKey) && effectiveKey.startsWith('sb_secret_')) {
    const message =
      'Supabase client is configured with a secret/service_role key on the frontend. ' +
      'Use only the browser-safe publishable/anon key for client-side requests.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_URL || !effectiveKey) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!effectiveKey ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, effectiveKey, {
    global: {
      fetch: createSupabaseFetch(effectiveKey),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

